add worker liveness support for flasher
metal-toolbox/flasher pull request #15
Opened 2023-05-26 19:46 UTC by DoctorVin

#### What does this PR do

2023-05-29 11:56 UTC, joelrebel requested changes
Thanks for the work here, left a minor comment,

2023-05-29 11:56 UTC, joelrebel commented on internal/worker/liveness.go
> +		go w.checkinRoutine(ctx)
Do we want a `w.syncWG.Add(1)`, and a related `defer w.syncWG.Done()` in `checkinRoutine` ?

2023-05-29 14:42 UTC, DoctorVin commented
That would send multiple Done calls for a single workgroup Add. I use the context’s validity to control running the go-routine, i.e. the go-routine stops when the context is cancelled. Adding this to the sync group isn’t useful here, as the go-routine does not have to stop gracefully.On May 29, 2023, at 7:57 AM, Joel Rebello ***@***.***> wrote:﻿
@joelrebel requested changes on this pull request.

Thanks for the work here, left a minor comment,

In internal/worker/liveness.go:
> +
+// This starts a go-routine to peridocally check in with the NATS kv
+func (w *Worker) startWorkerLivenessCheckin(ctx context.Context) {
+	natsJS, ok := w.stream.(*events.NatsJetstream)
+	if !ok {
+		w.logger.Error("Non-NATS stores are not supported for worker-liveness")
+		return
+	}
+
+	once.Do(func() {
+		if err := registry.InitializeActiveControllerRegistry(natsJS); err != nil {
+			w.logger.WithError(err).Error("unable to initialize active worker registry")
+			return
+		}
+
+		go w.checkinRoutine(ctx)

Do we want a w.syncWG.Add(1), and a related defer w.syncWG.Done() in checkinRoutine ?

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

2023-05-30 08:32 UTC, joelrebel approved these changes

2023-05-30 13:31 UTC, merged