Statemachine, task refactor
metal-toolbox/flasher pull request #150
Opened 2024-04-17 04:40 UTC by joelrebel

#### What does this PR do

Prep work to support task restarts, inband firmware installs.

- Moves away from the [stateswitch](https://github.com/filanov/stateswitch) library, to internal packages.
- Refactors `Task` objects for KV storage.
- Adds `Steps` as the smallest unit of work in a `Task` `Action`. 
- Use `github.com/stretchr/testify/mock` instead of `go.uber.org/mock/gomock`.
- Updates `export` CLI command for current Flasher flow diagram.

The commits in this PR are grouped by the kind of changes, recommend reviewing in commit order.

2024-04-22 14:25 UTC, DoctorVin requested changes
I was cool with everything until I got to "Flasher needs to encrypt BMC credentials." I think giving Flasher that responsibility is outside the scope of its work, and it will be a red flag for a lot of folks.

2024-04-22 14:25 UTC, DoctorVin commented on internal/worker/worker.go
> +	// TODO: encrypt BMC credentials before store in prod
We can't leave that as a `TODO`. Flasher should not encrypt anything on its own for any storage. It should always get credentials for the BMC from FleetDB.

2024-04-23 14:30 UTC, joelrebel commented on internal/model/publisher.go
> +// TODO: this needs to publish the whole task to the KV
yep, that would be the next round of work

2024-04-23 14:32 UTC, joelrebel commented on internal/install/task_handler.go
> +	// Setting this causes the action SM to not download the file
yeah, this is when `flasher install` is invoked with, 
```
flasher install  ... --file blob.bin 
```

2024-04-23 14:43 UTC, joelrebel commented on internal/model/task.go
> +	TaskVersion = "0.1"
I though `0.1` is valid semver?

2024-04-23 17:34 UTC, DoctorVin commented on internal/install/task_handler.go
> +	// Setting this causes the action SM to not download the file
I guess my question is: where does that blob come from? If this is an inband thing, then the out-of-band partner downloads it? Or does this get shipped through NATS? If the latter, I think we'll have problems due to the lack of storage we have in the hollow NATS cluster.

2024-04-23 17:34 UTC, DoctorVin commented on internal/model/task.go
> +	TaskVersion = "0.1"
It is, but it's also pre-release.

2024-04-23 17:36 UTC, DoctorVin commented on internal/worker/worker.go
> +	// TODO: encrypt BMC credentials before store in prod
Can you kill that `TODO` line then please? Just so any folks who might be snooping on our code don't get a Wrong Idea? tyvm.

2024-04-25 11:55 UTC, joelrebel commented on internal/model/firmware.go
> +// nolint:govet // fieldalignment struct is easier to read in the current format
We can do that once its moved to the shared CI linter configuration.

2024-04-25 11:57 UTC, joelrebel commented on internal/install/task_handler.go
> +	// Setting this causes the action SM to not download the file
The `flasher install` command is meant to be invoked by an operator manually. Its used to test/install updates without the whole NATS shebang.

2024-04-25 11:58 UTC, joelrebel commented on internal/model/task.go
> +	TaskVersion = "0.1"
ah, now I get what you mean there, I tend to be conservative with versioning, will bump to `1.0` instead.

2024-04-25 15:52 UTC, joelrebel commented
rebase on main

2024-04-25 16:20 UTC, DoctorVin submitted a review, later dismissed

2024-04-26 10:23 UTC, joelrebel commented
Since I cherry-picked commits from main in the previous rebase attempt, the conflicts with main couldn't be resolved.
This force push includes a proper rebase on main.

2024-04-26 12:03 UTC, merged